### ISSUE TITLE
irrlicht 1.8 and .NET 7

### ISSUE THREAD

**Issue by blender-girl** [slater1/blog#1]
Hi

Would it be possible to port your fantastic library so it supports latest irrlicht 1.8 and also .NET 7?

Thx

**Comment by slater1** [comment]
Hopfully it's as easy as changing the TFM from `netcoreapp3.1` to `net7.0-windows`. 

It does already target `netcoreapp3.1` which you should be able to reference from a `net7.0-windows` assembly

https://www.nuget.org/packages/Irrlicht.NetCore.x64

**Comment by blender-girl** [comment]
Thanks i try it!

.net core will be dropped by microsoft I have read (or maybe already is).

Will you try to make .net 7 version?

Do you know if original irrlicht lime project is abandoned?

**Comment by blender-girl** [comment]
Is it possible to allow issues in the irrlicht lime fork? They are disabled.

I want to test it and report problems I find

**Comment by slater1** [comment]
Fixed, sorry about that, I never noticed issues were disabled!

I have made some custom changes in this fork. Mostly around setting the absolute position of scene nodes. The default behavior is unchanged.

I haven't updated the irrlicht version since forking irrlicht lime in 2020.

I don't see any activity on the original repo since 2019.

**Comment by slater1** [comment]
And yes, netcoreapp3.1 is out of supports since a few weeks ago

**Comment by blender-girl** [comment]
Do you want to check if there are things not included/updated yet so irrrlicht latest version is supported?

**Comment by slater1** [comment]
I will check, but I don't have much personally invested. I welcome your contributions!

**Comment by blender-girl** [comment]
Unfortunately I csn just use irrlicht and am not good enough to contribute to this :(

**Comment by slater1** [comment]
I've updated irrlicht to the latest copy from the mirror at https://gitlab.com/pgimeno/irrlicht-mirror.
Then, I updated my fork off irrlicht lime (Irrlicht.Net) to target net6.0-windows and use vs2022 cpp toolset (v143; it was v142). Everything compiled but I did not run it.

my fork of irrlicht: https://github.com/slater1/Irrlicht
used by my fork of irrlicht lime: https://github.com/slater1/Irrlicht.Net

**Comment by slater1** [comment]
Can confirm it works. Tested with [GraphicsTemplate](https://github.com/slater1/GraphicsTemplate/)

![image](https://user-images.githubusercontent.com/2089725/212421008-5fe1922f-5cf8-4221-beb9-8653c0ad3a84.png)

A call to `GUIEnvironment.AddImage(...)` threw an `AccessViolationException`. I don't have time to look into it. I commented it out in the app.

Be sure to copy `Ijwhost.dll` and `Irrlicht.dll` from `Irrlicht.NetCore\bin\x64\Release`. This is done automatically with the nuget packages but net6.0-windows isn't published (yet)

**Comment by blender-girl** [comment]
Thanks, I have the same result so I did it correctly :)
Can I ask why you stay with .NET 6.0 and not use 7.0?

**Comment by blender-girl** [comment]
Maybe it's a good idea to move the examples from irrlicht lime to your repo once they all are working?

**Comment by slater1** [comment]
Great that it works for you too! I chose 6.0 because it it supported longer than 7.0. https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

I suppose it would be good to port some examples. I haven't because I don't need it and my fork is pretty obscure. But if it gathers interest it makes sense to.
